using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExamenModuloC.Model
{
    internal class Cotizacion : Interface.ICotizacionDTO
    {
        private int id;
        private DateTime dateTime;
        private int idVendedor;
        private Interface.IPrenda item;
        private int itemAmount;
        private double total;

        public int Id { get { return this.id; } set => this.id = value; }

        public DateTime DateTime { get { return this.dateTime; } set => this.dateTime = value; }

        public int IdVendedor { get { return this.idVendedor; } set => this.idVendedor = value; }

        public Interface.IPrenda Item { get { return this.item; } set => this.item = value; }

        public int ItemAmount { get { return this.itemAmount; } set => this.itemAmount = value; }

        public double Total { get { return this.total; } set => this.total = value; }

        public Cotizacion(int id, DateTime dateTime, int idVendedor, Interface.IPrenda item, int itemAmount, double total)
        {
            this.id = id;
            this.dateTime = dateTime;
            this.idVendedor = idVendedor;
            this.item = item;
            this.itemAmount = itemAmount;
            this.total = total;
        }
        //Unsaved cotizacion (id wasn't generated by the db yet)
        public Cotizacion(DateTime dateTime, int idVendedor, Interface.IPrenda item, int itemAmount, double total)
        {
            this.id = -1;
            this.dateTime = dateTime;
            this.idVendedor = idVendedor;
            this.item = item;
            this.itemAmount = itemAmount;
            this.total = total;
        }

        public override string ToString()
        {
            return $"Fecha y hora: {this.dateTime} Item: {this.item} Cantidad: {this.itemAmount} Total: {this.total}";
        }
    }
}
